#!/bin/bash
#
# by: Ricky A. Melgares '11, May 3, 2009
#
# File: indexer_test.sh
# Description: This simple script file which does:
# Step 1:
#   Pass in wrong arguments and see what happens
# Step 2:
#   Test for wrong specified directory.
# Step 3:
#   Let indexer to a full index on all files in a directory generated by the crawler.
# Step 4:
#   Compare the contents of the index.dat file and the re-created indexR.dat file

# Step 1
echo "Step 1"
echo "Wrong arguments number"
./indexer ./data
if [ $? -ne 1 ]; then
	echo "Return value wrong!"
fi
echo "Pass Step 1"

# Step 2
echo "Step 2"
echo "Wrong directory"
./indexer ./dataaaa index.dat
if [ $? -ne 1 ]; then
	echo "Return value wrong!"
fi
echo "Pass Step 2"

# Step 3
echo "Step 3"
echo "Real indexing job............."
filename=`date`
filename=$filename".log"
./indexer ../../data index.dat >> "$filename"
echo "Pass Step 3"

# Step 4
echo "Step 4"
echo "Comparing original index.dat file and the re-created index.dat file"
diff -u ../../data/index.dat ../../data/index_R.dat
if [ $? -ne 0 ]; 
	then
	echo "Return value wrong!"
else
	echo "They are the same!"
fi
echo "Pass Step 4"